language: scala

scala:
  - 2.11.8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
jdk:
  - oraclejdk8
services:
  - docker
before_script:
   - gem install travis
after_script:
   - curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
   - chmod +x trigger.sh
   - ./trigger.sh EmilDafinov scala-ad-sdk-client-smoke-tests master $TRAVIS_ACCESS_TOKEN 
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" emildafinov-docker-docker.bintray.io &&
    sbt clean docker:publish
