language: scala
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
scala:
- 2.12.1
jdk:
- oraclejdk8
services:
- docker
env:
  matrix:
    secure: YBLzk1sYGcNYPqSaTt3Xl9HseTtE/Hz42dTtsUmsdIV7IemWZCjXjY2WFAKI6kulnCRRU8XEB181xNCgf5b+mrXRO40snrdMFqGk7ADu4rhILUP+l4C8VXbSfG5u949jiMi04O5MNL5BzGEAoG26wbLvehN5pu1MxUjUOOIRfXSGu5MuDSUMRhYWKjl+XLXKOn5SOGZ2c4aTIoNF0I3MOWPVW1qdbkzaM94U9A6j4oGGUXJFsPYuErpP1Wi6fnZHuGC57Q7+3J1LDUtq+bYJH0k86PcbYwjkmqEZb0BMbNmpaVQ7AmhIU99XUB+W+wZj7CnXWNO07mO8P1jHNWoxtKUtDBhvMOE9rZRfS/9BQrw6nMaTTYGHg/K731vgJ4dtJKBF+l6yJfsnnVuTTPIL45mObkwcix+r2l1k1XkzrKWu9FB7RYimOePCI8qDmXvxNiNiwapRRCyrSuN0Mr/dM8rgEzuABePK79SBGm0Pg0wdGNVmtUu3U188Su5+Ky359MOdEfOrIBtNy+ztCCHuH5s2isUztqMsL9pvgq+ORzKSHcxyC6/dBgOGwh9UWtG9q71iXTq6JiVzI0REGPgptmM5DjTrSKGVy2JgMQl4II3GREy+Qvxjb+ZqN++lu/F1TstZqzgF3BJ83mx+sfeiGEyxtt9C5G1Y3zF+GSMtio8=
after_success:
- sbt docker:publishLocal
- docker login -u emildafinov -p ++$API_KEY -e ++$EMAIL emildafinov-docker-emiliorodo-docker.bintray.io
- docker push emildafinov-docker-emiliorodo-docker.bintray.io/scala-ad-sdk-client:0.1
